version: '3.8'

services:
    wayward-db:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "${database.rootPass}"
            MYSQL_DATABASE: "${database.name}"
            MYSQL_USER: "${database.username}"
            MYSQL_PASSWORD: "${database.password}"
        volumes:
            - wayward-db-data:/var/lib/mysql
            - ./src/main/resources/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

    wayward-api:
        image: wayward-cookies-api:latest
        cap_add:
            - SYS_NICE
        restart: always
        ports:
            - '3306:3306'
        environment:
            database.url: "${database.url}"
            database.username: "${database.username}"
            database.password: "${database.password}"
            
volumes:
    wayward-db-data: