version: '3.8'

services:
    wayward-db:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: wayward
            MYSQL_DATABASE: wayward
            MYSQL_USER: wayward
            MYSQL_PASSWORD: wayward
        volumes:
            - wayward-db-data:/var/lib/mysql
            - ./src/main/resources/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    wayward-db-data: