name: Build With Maven

on:
  push:
    branches: [ "main" ]

jobs:
  Main:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push To Docker.io
        with:
          image: cheezballs/wayward-cookies-api
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: appleboy/ssh-action@master
        name: Deploying on Davos
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: bash /deploy/wayward-cookies/wayward-refresh.sh